from pydantic import BaseModel


class BlumBibItem(BaseModel):
    _to_do_general: str
    _change_request: str
    entry_type: str
    bibkey: str
    author: str
    _author_ids: str
    editor: str
    _editor_ids: str
    author_ids: str
    options: str
    shorthand: str
    date: str
    pubstate: str
    title: str
    _title_unicode: str
    booktitle: str
    crossref: str
    journal: str
    journal_id: str
    volume: str
    number: str
    pages: str
    eid: str
    series: str
    address: str
    institution: str
    school: str
    publisher: str
    publisher_id: str
    type: str
    edition: str
    note: str
    _issuetitle: str
    _guesteditor: str
    _extra_note: str
    urn: str
    eprint: str
    doi: str
    url: str
    _kw_level1: str
    _kw_level2: str
    _kw_level3: str
    _epoch: str
    _person: str
    _comm_for_profile_bib: str
    _langid: str
    _lang_der: str
    _further_refs: str
    _depends_on: str
    _dltc_num: str
    _spec_interest: str
    _note_perso: str
    _note_stock: str
    _note_status: str
    _num_inwork_coll: str
    _num_inwork: str
    _num_coll: str
    _dltc_copyediting_note: str
    _note_missing: str
    _num_sort: str
